Stage EC2 Deploy

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -115,7 +115,7 @@ pipeline {
             }
           }
         }
-        stage('Init - Get EC2 IP') {
+        stage('Deploy-AWS EC2') {
           steps {
             withAWS(credentials: 'AWS managing Credentials', region: 'eu-north-1') {
               script {
@@ -127,38 +127,30 @@ pipeline {
                   returnStdout: true
                 ).trim()
                 echo "Captured IP: ${env.PUBLIC_IP}"
+
+                sshagent(['aws-ec2']) {
+                   sh """ 
+                      ssh -o StrictHostKeyChecking=no ec2-user@${env.PUBLIC_IP}"
+                        if ! command -v docker >/dev/null; then
+                           echo "Docker not found. Installing..."
+                           sudo yum update -y
+                           sudo yum install -y docker
+                           sudo systemctl start docker
+                           sudo usermod -aG docker ec2-user
+                        fi
+
+                        if sudo docker ps -a | grep -q "solar-system"; then
+                           echo "Container found. Stopping..."
+                           sudo docker stop solar-system && sudo docker rm solar-system
+                           echo "Container stopped and removed."
+                        fi
+
+                        sudo docker run --name solar-system -p 3000:3000 -d ek89/solar-system:$GIT_COMMIT
+                      "
+                   """
+                }       
               }
             }
-          }
-        } 
-        stage('Deploy - AWS EC2') {
-          when {
-             branch 'feature/*'
-          }
-          steps {
-              script {
-                  sshagent(['aws-ec2']) {
-                     sh """ 
-                        ssh -o StrictHostKeyChecking=no ec2-user@${publicIp}"
-                          if ! command -v docker >/dev/null; then
-                             echo "Docker not found. Installing..."
-                             sudo yum update -y
-                             sudo yum install -y docker
-                             sudo systemctl start docker
-                             sudo usermod -aG docker ec2-user
-                          fi
-
-                          if sudo docker ps -a | grep -q "solar-system"; then
-                             echo "Container found. Stopping..."
-                             sudo docker stop solar-system && sudo docker rm solar-system
-                             echo "Container stopped and removed."
-                          fi
-
-                          sudo docker run --name solar-system -p 3000:3000 -d ek89/solar-system:$GIT_COMMIT
-                        "
-                     """       
-                  }
-              }
           }        
         }
         stage('Integration Testing - AWS EC2') {
